(function(){
  const SAVE='little-chemie8-save-v4';
  const START=['stoff','teilchen','energie','temperatur','modell','labor','wasser','sauerstoff','luft'];
  const LABEL={stoff:'Stoff',teilchen:'Teilchen',energie:'Energie',temperatur:'Temperatur',modell:'Modell',labor:'Labor',wasser:'Wasser',sauerstoff:'Sauerstoff',luft:'Luft',stoffgemisch:'Stoffgemisch',loesung:'Lösung',trennverfahren:'Trennverfahren',filtrieren:'Filtrieren',destillation:'Destillation',teilchenmodell:'Teilchenmodell',atom:'Atom',molekuel:'Molekül',element:'Element',verbindung:'Verbindung',reaktion:'Chemische Reaktion',edukt:'Edukt',produkt:'Produkt',schema:'Reaktionsschema',massenerhaltung:'Massenerhaltung',verbrennung:'Verbrennung',oxidation:'Oxidation',kohlenstoffdioxid:'Kohlenstoffdioxid',glimmspanprobe:'Glimmspanprobe',kalkwasserprobe:'Kalkwasserprobe',branddreieck:'Branddreieck',atmosphaere:'Atmosphäre',treibhausgas:'Treibhausgas',methan:'Methan',treibhauseffekt:'Treibhauseffekt',erwaermung:'Globale Erwärmung',ozon:'Ozon',ozonschicht:'Ozonschicht',uv:'UV-Strahlung',ozonloch:'Ozonloch',metall:'Metall',metalloxid:'Metalloxid',rost:'Rost',reduktion:'Reduktion',redox:'Redoxreaktion'};
  const TECHS=[
    {id:'grund',icon:'🧪',title:'Grundlagen',desc:'Startwissen: Stoffe, Teilchen, Energie und Labor.',needs:[],targets:['stoff','teilchen','energie','labor','wasser','sauerstoff','luft']},
    {id:'stoffe',icon:'🥣',title:'Stoffe trennen',desc:'Gemische, Lösungen und Trennverfahren erforschen.',needs:['grund'],targets:['stoffgemisch','loesung','trennverfahren','filtrieren','destillation']},
    {id:'teil',icon:'⚛️',title:'Teilchenwelt',desc:'Von Teilchen zu Atom, Molekül, Element und Verbindung.',needs:['grund'],targets:['teilchenmodell','atom','molekuel','element','verbindung']},
    {id:'reak',icon:'✨',title:'Reaktionslehre',desc:'Edukte, Produkte, Reaktionsschema und Massenerhaltung.',needs:['stoffe','teil'],targets:['reaktion','edukt','produkt','schema','massenerhaltung']},
    {id:'brand',icon:'🔥',title:'Feuer & Nachweise',desc:'Verbrennung, Oxidation und Gasnachweise.',needs:['reak'],targets:['verbrennung','oxidation','kohlenstoffdioxid','glimmspanprobe','kalkwasserprobe','branddreieck']},
    {id:'umwelt',icon:'🌍',title:'Umweltchemie',desc:'Treibhauseffekt, Ozon, Ozonschicht und Ozonloch.',needs:['brand'],targets:['atmosphaere','treibhausgas','methan','treibhauseffekt','erwaermung','ozon','ozonschicht','uv','ozonloch']},
    {id:'redox',icon:'🔩',title:'Metalle & Redox',desc:'Metalloxide, Rost, Reduktion und Redoxreaktion.',needs:['brand'],targets:['metall','metalloxid','rost','reduktion','redox']}
  ];
  function ready(fn){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',fn);else fn()}
  function deck(){try{return[...new Set([...START,...JSON.parse(localStorage.getItem(SAVE)||'[]')])]}catch(e){return START}}
  function has(id){return deck().includes(id)}
  function complete(t){return t.targets.every(has)}
  function touched(t){return t.targets.some(has)}
  function available(t){return !t.needs.length||t.needs.every(n=>{const p=TECHS.find(x=>x.id===n);return p&&(complete(p)||touched(p))})}
  function progress(t){const found=t.targets.filter(has).length;return{found,total:t.targets.length,pct:Math.round(found/t.targets.length*100)}}
  function era(){const done=TECHS.filter(complete).length;if(done>=6)return'Industrie der Ideen';if(done>=4)return'Reaktionszeitalter';if(done>=2)return'Teilchenzeitalter';return'Entdeckerzeit'}
  function science(){return deck().length*10}
  function label(id){return LABEL[id]||id}
  function insertPanel(){if(document.getElementById('researchPanel'))return;const missions=document.querySelector('.panel');if(!missions)return;const panel=document.createElement('section');panel.id='researchPanel';panel.className='research-panel';panel.innerHTML='<div class="research-head"><div><h2>🧭 Forschungsbaum</h2><p>Wie bei Civilization: Erforsche einen Chemie-Zweig nach dem anderen. Gesperrte Zweige sind sichtbar, werden aber erst später nutzbar.</p></div><div class="research-score"><span id="scienceScore" class="science-pill">🔬 0 Forschung</span><span id="eraScore" class="era-pill">Entdeckerzeit</span></div></div><div id="techMap" class="tech-map"></div><div id="techTip" class="tech-tip">Tipp: Starte links und arbeite dich über Kombinationen nach rechts vor.</div>';missions.parentNode.insertBefore(panel,missions)}
  function renderResearch(){insertPanel();const map=document.getElementById('techMap');if(!map)return;map.innerHTML='';TECHS.forEach(t=>{const p=progress(t),isComplete=complete(t),isAvailable=available(t),state=isComplete?'complete':isAvailable?'available':'locked';const el=document.createElement('article');el.className='tech-node '+state+(state==='available'&&!isComplete?' current':'');el.dataset.tech=t.id;el.innerHTML=`<div class="tech-icon">${t.icon}</div><div class="tech-title">${t.title}</div><div class="tech-desc">${t.desc}</div><div class="tech-progress"><span style="width:${p.pct}%"></span></div><div class="tech-state">${isComplete?'Erforscht':isAvailable?'Forschbar':'Gesperrt'} · ${p.found}/${p.total}</div>`;el.onclick=()=>showTip(t,state);map.appendChild(el)});const s=document.getElementById('scienceScore'),e=document.getElementById('eraScore');if(s)s.textContent='🔬 '+science()+' Forschung';if(e)e.textContent=era()}
  function showTip(t,state){const tip=document.getElementById('techTip');if(!tip)return;if(state==='locked'){const needs=t.needs.map(id=>TECHS.find(x=>x.id===id)?.title||id).join(', ');tip.innerHTML='🔒 <b>'+t.title+'</b> ist noch gesperrt. Erforsche zuerst: <b>'+needs+'</b>.';return}const missing=t.targets.filter(id=>!has(id));if(!missing.length){tip.innerHTML='✅ <b>'+t.title+'</b> ist vollständig erforscht. Sehr stark!';return}tip.innerHTML='🧭 <b>'+t.title+'</b>: Noch offen sind <b>'+missing.slice(0,4).map(label).join(', ')+'</b>'+ (missing.length>4?' …':'') +'. Nutze Kombinationen und Tipps.'}
  ready(()=>{insertPanel();renderResearch();setInterval(renderResearch,800)})
})();